//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusOn.Framework.Business.Services.Localizations {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FocusOn.Framework.Business.Services.Localizations.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 实体 &apos;{0}&apos; 没有找到 的本地化字符串。
        /// </summary>
        internal static string Message_EntityNotFound {
            get {
                return ResourceManager.GetString("Message_EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库保存失败 的本地化字符串。
        /// </summary>
        internal static string Message_SaveChangesFailed {
            get {
                return ResourceManager.GetString("Message_SaveChangesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库保存返回行数是 0 的本地化字符串。
        /// </summary>
        internal static string Message_SaveChangesRowIsZero {
            get {
                return ResourceManager.GetString("Message_SaveChangesRowIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库保存成功 的本地化字符串。
        /// </summary>
        internal static string Message_SaveChangesSuccessfully {
            get {
                return ResourceManager.GetString("Message_SaveChangesSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 &apos;{0}&apos; 创建成功 的本地化字符串。
        /// </summary>
        internal static string Message_User_Created {
            get {
                return ResourceManager.GetString("Message_User_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 &apos;{0}&apos; 重复 的本地化字符串。
        /// </summary>
        internal static string Message_User_EmailDuplicate {
            get {
                return ResourceManager.GetString("Message_User_EmailDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号 &apos;{0}&apos; 重复 的本地化字符串。
        /// </summary>
        internal static string Message_User_MobileDuplicate {
            get {
                return ResourceManager.GetString("Message_User_MobileDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 &apos;{0}&apos; 重复 的本地化字符串。
        /// </summary>
        internal static string Message_User_UserNameDuplicate {
            get {
                return ResourceManager.GetString("Message_User_UserNameDuplicate", resourceCulture);
            }
        }
    }
}
